### PR TITLE
New option to show/hide signal quality icon for wireless devices

### PR DESCRIPTION
**Pull request by monsta**
@NiceandGently @flexiondotorg @infirit @stefano-k
please test it (if you have any wifi devices)  :smile:

### CODE REVIEW

**Comment by NiceandGently** [comment]
ok, applet loads now , but i don't see the signal quality icon
.... or do i miss something....

**Comment by monsta** [comment]
Well... this is a stupid question, but did you select the wireless device in the combobox in the prefs dialog?

**Comment by reddot15** [comment]
i have this problem, im unable to remove the annoying blue wifi icon that shows up in version 1.10, y in only in wifi device mode, or default if default is wifi.

**Comment by NiceandGently** [comment]
> Well... this is a stupid question, but did you select the wireless device in the combobox in the prefs dialog?
Of course wifi is selected in combobox.

**Comment by monsta** [comment]
**Important**: mate-netspeed should be built with wireless support, or else you won't even see the signal quality icon and other wifi-related stuff.

**Pull request merged**
